# Generated by Django 5.1.5 on 2026-02-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('score_weights', models.JSONField(default=dict, help_text='Expected keys: eligibility, feasibility, urgency, explainability')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
