# Generated by Django 5.1.5 on 2026-02-07 22:33

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='clinicaltrials.gov', max_length=64)),
                ('trial_id', models.CharField(max_length=64, unique=True)),
                ('title', models.TextField()),
                ('phase', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('RECRUITING', 'Recruiting'), ('NOT_YET_RECRUITING', 'Not Yet Recruiting'), ('ACTIVE_NOT_RECRUITING', 'Active, Not Recruiting'), ('COMPLETED', 'Completed')], default='RECRUITING', max_length=64)),
                ('conditions', models.JSONField(default=list)),
                ('interventions', models.JSONField(default=list)),
                ('countries', models.JSONField(default=list)),
                ('sponsor', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('eligibility_summary', models.TextField(blank=True)),
                ('inclusion_text', models.TextField(blank=True)),
                ('exclusion_text', models.TextField(blank=True)),
                ('eligibility_json', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('embedding_text', models.TextField(blank=True)),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('external_last_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrialSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='trials.trial')),
            ],
            options={
                'unique_together': {('trial', 'facility', 'city', 'country')},
            },
        ),
    ]
