# Generated by Django 5.1.5 on 2026-02-07 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_type', models.CharField(default='scheduled', max_length=32)),
                ('status', models.CharField(default='running', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligibility_score', models.PositiveSmallIntegerField(default=0)),
                ('feasibility_score', models.PositiveSmallIntegerField(default=0)),
                ('urgency_score', models.PositiveSmallIntegerField(default=0)),
                ('explainability_score', models.PositiveSmallIntegerField(default=0)),
                ('urgency_flag', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=16)),
                ('overall_status', models.CharField(choices=[('Eligible', 'Eligible'), ('Possibly Eligible', 'Possibly Eligible'), ('Unlikely', 'Unlikely')], default='Possibly Eligible', max_length=32)),
                ('reasons_matched', models.JSONField(default=list)),
                ('reasons_failed', models.JSONField(default=list)),
                ('missing_info', models.JSONField(default=list)),
                ('doctor_checklist', models.JSONField(default=list)),
                ('explanation_summary', models.TextField(blank=True)),
                ('explanation_language', models.CharField(default='en', max_length=16)),
                ('explanation_model', models.CharField(blank=True, max_length=255)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('outreach_status', models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('replied', 'Replied'), ('no_response', 'No Response')], default='pending', max_length=32)),
                ('vector_similarity', models.FloatField(default=0.0)),
                ('last_evaluated', models.DateTimeField(auto_now=True)),
                ('is_new', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='patients.patientprofile')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='trials.trial')),
                ('matching_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_evaluations', to='matching.matchingrun')),
            ],
            options={
                'unique_together': {('patient', 'trial')},
            },
        ),
    ]
