# Generated by Django 5.1.5 on 2026-02-07 22:33

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_code', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('language', models.CharField(default='English', max_length=32)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(blank=True, max_length=255)),
                ('story', models.TextField(blank=True)),
                ('structured_profile', models.JSONField(default=dict)),
                ('contact_channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Phone')], max_length=32)),
                ('contact_value', models.CharField(max_length=255)),
                ('consent', models.BooleanField(default=False)),
                ('profile_completeness', models.PositiveSmallIntegerField(default=0)),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
