# Generated by Django 5.1.5 on 2026-02-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patientdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdocument",
            name="extracted_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="extraction_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("extracted", "Extracted"),
                    ("unsupported", "Unsupported"),
                    ("empty", "Empty"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
