# Generated by Django 5.1.5 on 2026-02-08 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patientdocument_extraction_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientHistoryEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("intake", "Intake"), ("patient_portal", "Patient Portal"), ("coordinator", "Coordinator")],
                        default="patient_portal",
                        max_length=32,
                    ),
                ),
                ("entry_text", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
