SAMPLE_TRIALS = [
    {
        "trial_id": "NCT06812345",
        "source": "clinicaltrials.gov",
        "title": "A Phase III Study of Trastuzumab Deruxtecan vs Physician's Choice in HER2+ Metastatic Breast Cancer",
        "phase": "Phase 3",
        "status": "RECRUITING",
        "conditions": ["Breast Cancer", "HER2+ Breast Cancer", "Metastatic"],
        "interventions": ["Trastuzumab Deruxtecan", "Physician's Choice Chemo"],
        "countries": ["Pakistan", "UAE"],
        "sponsor": "Daiichi Sankyo",
        "summary": "Evaluates efficacy and safety in HER2-positive metastatic breast cancer.",
        "eligibility_summary": "Adults 18+, HER2+, prior anti-HER2 therapy, ECOG 0-1.",
        "inclusion_text": "Age >=18, HER2+, prior anti-HER2 therapy, ECOG <=1",
        "exclusion_text": "Uncontrolled CNS metastases",
        "sites": [
            {"facility": "Aga Khan University Hospital", "city": "Karachi", "country": "Pakistan"},
            {"facility": "Cleveland Clinic Abu Dhabi", "city": "Abu Dhabi", "country": "UAE"},
        ],
        "source_url": "https://clinicaltrials.gov/study/NCT06812345",
    },
    {
        "trial_id": "NCT07234567",
        "source": "clinicaltrials.gov",
        "title": "Pembrolizumab Combined with Chemotherapy for TNBC in South Asian Population",
        "phase": "Phase 2",
        "status": "RECRUITING",
        "conditions": ["Triple-Negative Breast Cancer", "Locally Advanced"],
        "interventions": ["Pembrolizumab", "Nab-Paclitaxel"],
        "countries": ["Pakistan", "Saudi Arabia"],
        "sponsor": "MSD",
        "summary": "Combination immunotherapy in TNBC patients.",
        "eligibility_summary": "Adults 18-70, TNBC, Stage IIB-IIIC, PD-L1 >=10, ECOG 0-1.",
        "inclusion_text": "TNBC, Stage IIB-IIIC, PD-L1 >=10, ECOG <=1",
        "exclusion_text": "Prior systemic therapy",
        "sites": [{"facility": "PIMS", "city": "Islamabad", "country": "Pakistan"}],
        "source_url": "https://clinicaltrials.gov/study/NCT07234567",
    },
    {
        "trial_id": "DRAP-2026-0042",
        "source": "pakistan_ctr",
        "title": "Sacituzumab Govitecan in Pre-Treated Metastatic Breast Cancer",
        "phase": "Phase 2",
        "status": "RECRUITING",
        "conditions": ["Metastatic Breast Cancer", "TNBC"],
        "interventions": ["Sacituzumab Govitecan"],
        "countries": ["Pakistan"],
        "sponsor": "DRAP",
        "summary": "Registry study in pre-treated metastatic breast cancer.",
        "eligibility_summary": "Adults 18+, >=2 prior lines, ECOG 0-2.",
        "inclusion_text": "At least 2 prior lines, ECOG <=2",
        "exclusion_text": "Active brain metastases",
        "sites": [{"facility": "JPMC", "city": "Karachi", "country": "Pakistan"}],
        "source_url": "https://ctr.dra.gov.pk",
    },
]
